import { Project, AdhocRequest, AuditEntry, deriveStatus } from "./types";

const Q_START = new Date("2025-01-06");
const d = (offset: number) => {
  const x = new Date(Q_START);
  x.setDate(x.getDate() + offset);
  return x.toISOString();
};

type SeedProj = Omit<Project, "status" | "deliveryHistory"> & { delivered?: boolean };

const raw: SeedProj[] = [
  { id: "p1", name: "Continue Watching v2", businessPoc: "Sanjay Bhatt", productPoc: "Aanya Sharma", successMetric: "+8% session resume rate", kind: "planned", category: "Subscription", priority: 1,
    plannedResources: { E: 3, T: 2, D: 1 }, currentResources: { E: 2, T: 2, D: 1 },
    startDate: d(0), targetDate: d(35), newDate: d(49), progress: 62, delayReason: "adhoc", impactedBy: ["r1"], quarter: "Q1" },
  { id: "p2", name: "Personalized Hero Rail", businessPoc: "Neha Verma", productPoc: "Rohan Mehta", successMetric: "+12% homepage CTR", kind: "planned", category: "Personalization", priority: 1,
    plannedResources: { E: 4, T: 2, D: 2 }, currentResources: { E: 4, T: 2, D: 2 },
    startDate: d(7), targetDate: d(56), newDate: d(56), progress: 48, quarter: "Q1" },
  { id: "p3", name: "Ad Break Optimization", businessPoc: "Karan Joshi", productPoc: "Priya Iyer", successMetric: "+5% ad fill rate", kind: "planned", category: "Ads", priority: 2,
    plannedResources: { E: 2, T: 1, D: 0 }, currentResources: { E: 2, T: 1, D: 0 },
    startDate: d(0), targetDate: d(28), newDate: d(28), progress: 100, quarter: "Q1", delivered: true },
  { id: "p4", name: "Frequency Capping Engine", businessPoc: "Karan Joshi", productPoc: "Vikram Singh", successMetric: "Reduce ad fatigue 20%", kind: "planned", category: "Ads", priority: 1,
    plannedResources: { E: 3, T: 2, D: 1 }, currentResources: { E: 2, T: 2, D: 1 },
    startDate: d(14), targetDate: d(63), newDate: d(70), progress: 35, delayReason: "scope_change", quarter: "Q1" },
  { id: "p5", name: "Subscriber Onboarding Redesign", businessPoc: "Neha Verma", productPoc: "Meera Krishnan", successMetric: "+15% activation", kind: "planned", category: "Engagement", priority: 2,
    plannedResources: { E: 2, T: 1, D: 2 }, currentResources: { E: 2, T: 1, D: 2 },
    startDate: d(0), targetDate: d(42), newDate: d(42), progress: 70, quarter: "Q1" },
  { id: "p6", name: "Family Profiles", businessPoc: "Sanjay Bhatt", productPoc: "Arjun Kapoor", successMetric: "+6% household retention", kind: "planned", category: "Personalization", priority: 3,
    plannedResources: { E: 2, T: 1, D: 1 }, currentResources: { E: 2, T: 1, D: 1 },
    startDate: d(21), targetDate: d(70), newDate: d(70), progress: 22, quarter: "Q1" },
  { id: "p7", name: "Watch Party Beta", businessPoc: "Neha Verma", productPoc: "Sneha Reddy", successMetric: "Launch beta to 5k users", kind: "planned", category: "Engagement", priority: 3,
    plannedResources: { E: 3, T: 1, D: 1 }, currentResources: { E: 3, T: 1, D: 1 },
    startDate: d(28), targetDate: d(84), newDate: d(91), progress: 15, delayReason: "adhoc", impactedBy: ["r5"], quarter: "Q1" },
  { id: "p8", name: "Bid Floor Experiments", businessPoc: "Karan Joshi", productPoc: "Karan Joshi", successMetric: "+3% eCPM", kind: "planned", category: "Ads", priority: 2,
    plannedResources: { E: 2, T: 1, D: 0 }, currentResources: { E: 2, T: 1, D: 0 },
    startDate: d(7), targetDate: d(49), newDate: d(49), progress: 55, quarter: "Q1" },
  { id: "p9", name: "Referral Program v3", businessPoc: "Sanjay Bhatt", productPoc: "Divya Nair", successMetric: "+10% referred signups", kind: "planned", category: "Miscellaneous", priority: 2,
    plannedResources: { E: 2, T: 1, D: 1 }, currentResources: { E: 2, T: 1, D: 1 },
    startDate: d(14), targetDate: d(56), newDate: d(56), progress: 40, quarter: "Q1" },
  { id: "p10", name: "Offline Downloads HDR", businessPoc: "Neha Verma", productPoc: "Aanya Sharma", successMetric: "Enable HDR offline", kind: "planned", category: "Subscription", priority: 2,
    plannedResources: { E: 3, T: 2, D: 0 }, currentResources: { E: 3, T: 2, D: 0 },
    startDate: d(35), targetDate: d(84), newDate: d(89), progress: 8, delayReason: "adhoc", impactedBy: ["r8"], quarter: "Q1" },
  { id: "p11", name: "Brand Safety Filters", businessPoc: "Karan Joshi", productPoc: "Priya Iyer", successMetric: "Block 99% unsafe inventory", kind: "planned", category: "Ads", priority: 1,
    plannedResources: { E: 2, T: 2, D: 0 }, currentResources: { E: 2, T: 2, D: 0 },
    startDate: d(0), targetDate: d(35), newDate: d(35), progress: 100, quarter: "Q1", delivered: true },
  { id: "p12", name: "Payment Retry Engine", businessPoc: "Sanjay Bhatt", productPoc: "Meera Krishnan", successMetric: "Recover 4% failed payments", kind: "planned", category: "Subscription", priority: 1,
    plannedResources: { E: 3, T: 2, D: 0 }, currentResources: { E: 3, T: 2, D: 0 },
    startDate: d(7), targetDate: d(63), newDate: d(63), progress: 50, quarter: "Q1" },

  // ── 5 new planned projects ──────────────────────────────────────────────────
  { id: "p13", name: "Smart Content Tagging", businessPoc: "Neha Verma", productPoc: "Aanya Sharma", successMetric: "Auto-tag 95% of catalog", kind: "planned", category: "AI", priority: 1,
    plannedResources: { E: 3, T: 1, D: 1 }, currentResources: { E: 3, T: 1, D: 1 },
    startDate: d(14), targetDate: d(70), newDate: d(75), progress: 45, delayReason: "adhoc", impactedBy: ["r6"], quarter: "Q1" },
  { id: "p14", name: "Multi-Language Subtitles", businessPoc: "Sanjay Bhatt", productPoc: "Divya Nair", successMetric: "+20% content accessibility score", kind: "planned", category: "Discovery", priority: 2,
    plannedResources: { E: 2, T: 1, D: 1 }, currentResources: { E: 2, T: 1, D: 1 },
    startDate: d(0), targetDate: d(42), newDate: d(56), progress: 55, delayReason: "scope_change", quarter: "Q1" },
  { id: "p15", name: "Subscriber Tier Upgrade Flow", businessPoc: "Sanjay Bhatt", productPoc: "Meera Krishnan", successMetric: "+18% tier upgrade conversions", kind: "planned", category: "Subscription", priority: 1,
    plannedResources: { E: 3, T: 2, D: 1 }, currentResources: { E: 3, T: 2, D: 1 },
    startDate: d(21), targetDate: d(77), newDate: d(84), progress: 30, delayReason: "adhoc", impactedBy: ["r7"], quarter: "Q1" },
  { id: "p16", name: "CTV Remote Navigation", businessPoc: "Karan Joshi", productPoc: "Vikram Singh", successMetric: "+10% CTV session time", kind: "planned", category: "Linear", priority: 2,
    plannedResources: { E: 2, T: 2, D: 1 }, currentResources: { E: 2, T: 2, D: 1 },
    startDate: d(7), targetDate: d(56), newDate: d(63), progress: 40, delayReason: "adhoc", impactedBy: ["r4"], quarter: "Q1" },
  { id: "p17", name: "Push Notification A/B Engine", businessPoc: "Neha Verma", productPoc: "Sneha Reddy", successMetric: "+25% notification open rate", kind: "planned", category: "Engagement", priority: 2,
    plannedResources: { E: 2, T: 1, D: 0 }, currentResources: { E: 2, T: 1, D: 0 },
    startDate: d(0), targetDate: d(28), newDate: d(28), progress: 100, quarter: "Q1", delivered: true },

  // ── 5 new adhoc projects ────────────────────────────────────────────────────
  { id: "ad1", name: "Cricket Live Stream Promo", businessPoc: "Sanjay Bhatt", productPoc: "Rohan Mehta", successMetric: "IPL final week takeover", kind: "adhoc", category: "Linear", priority: 1,
    plannedResources: { E: 1, T: 1, D: 0 }, currentResources: { E: 1, T: 1, D: 0 },
    startDate: d(28), targetDate: d(42), newDate: d(42), progress: 60, quarter: "Q1" },
  { id: "ad2", name: "Emergency Content Takedown Tool", businessPoc: "Priya Iyer", productPoc: "Arjun Kapoor", successMetric: "Remove flagged content in <1 hr", kind: "adhoc", category: "Miscellaneous", priority: 1,
    plannedResources: { E: 1, T: 1, D: 0 }, currentResources: { E: 1, T: 1, D: 0 },
    startDate: d(30), targetDate: d(44), newDate: d(44), progress: 80, quarter: "Q1" },
  { id: "ad3", name: "Awards Season Homepage Takeover", businessPoc: "Sanjay Bhatt", productPoc: "Rohan Mehta", successMetric: "+30% concurrent users handled on awards night", kind: "adhoc", category: "Engagement", priority: 1,
    plannedResources: { E: 2, T: 1, D: 1 }, currentResources: { E: 2, T: 1, D: 1 },
    startDate: d(50), targetDate: d(63), newDate: d(63), progress: 25, quarter: "Q1" },
  { id: "ad4", name: "Regional Language Quick Add", businessPoc: "Neha Verma", productPoc: "Divya Nair", successMetric: "Ship 3 new regional language packs in 2 weeks", kind: "adhoc", category: "Discovery", priority: 2,
    plannedResources: { E: 1, T: 1, D: 0 }, currentResources: { E: 1, T: 1, D: 0 },
    startDate: d(35), targetDate: d(49), newDate: d(49), progress: 55, quarter: "Q1" },
  { id: "ad5", name: "OTT Partner API Integration", businessPoc: "Karan Joshi", productPoc: "Vikram Singh", successMetric: "Go-live with 2 new telco partner bundles", kind: "adhoc", category: "Subscription", priority: 1,
    plannedResources: { E: 2, T: 1, D: 0 }, currentResources: { E: 2, T: 1, D: 0 },
    startDate: d(42), targetDate: d(63), newDate: d(63), progress: 38, quarter: "Q1" },
  { id: "ad6", name: "Live Event Score Overlay", businessPoc: "Sanjay Bhatt", productPoc: "Sneha Reddy", successMetric: "Real-time score overlay for 5 live events", kind: "adhoc", category: "Linear", priority: 2,
    plannedResources: { E: 1, T: 1, D: 0 }, currentResources: { E: 1, T: 1, D: 0 },
    startDate: d(55), targetDate: d(70), newDate: d(70), progress: 12, quarter: "Q1" },
];

export const seedProjects: Project[] = raw.map((p) => ({
  ...p,
  status: deriveStatus(p.targetDate, p.newDate, !!p.delivered),
  deliveryHistory: p.targetDate !== p.newDate ? [{
    id: `h-${p.id}`, timestamp: d(20), fromDate: p.targetDate, toDate: p.newDate,
    reason: p.delayReason ?? "estimation", actor: "system", requestId: p.impactedBy?.[0],
  }] : [],
}));

export const seedRequests: AdhocRequest[] = [
  { id: "r1", title: "Cricket Live Stream Promo", description: "Leadership wants a homepage takeover for the IPL final week with a live countdown and one-tap subscribe.",
    requestedBy: "Sanjay Bhatt", successMetric: "IPL final week takeover", urgency: "high", category: "Linear",
    resources: { E: 1, T: 1, D: 0 }, targetDate: d(42),
    impacts: [{ projectId: "p1", delayDays: 14, newDate: d(49) }],
    status: "approved", createdAt: d(20), decisionDeadline: d(22), decidedAt: d(21), decidedBy: "Neha Verma",
    decisionComment: "Strategic moment — proceed.", quarter: "Q1" },
  { id: "r2", title: "Compliance: New EU Ads Disclosure", description: "Regulatory requirement to add transparent ad disclosure UI before April rollout.",
    requestedBy: "Priya Iyer", successMetric: "EU regulatory compliance", urgency: "high", category: "Ads",
    resources: { E: 2, T: 1, D: 1 }, targetDate: d(60),
    impacts: [{ projectId: "p4", delayDays: 7, newDate: d(77) }, { projectId: "p8", delayDays: 5, newDate: d(54) }],
    status: "awaiting_reply", createdAt: d(40), decisionDeadline: d(44), quarter: "Q1" },
  { id: "r3", title: "Partner Launch: Reliance Bundle", description: "Bundle integration with telco partner — needs custom signup flow.",
    requestedBy: "Karan Joshi", successMetric: "Bundle 500k new subs", urgency: "medium", category: "Subscription",
    resources: { E: 2, T: 1, D: 1 }, targetDate: d(70),
    impacts: [{ projectId: "p5", delayDays: 10, newDate: d(52) }, { projectId: "p9", delayDays: 14, newDate: d(70) }],
    status: "awaiting_reply", createdAt: d(42), decisionDeadline: d(48), quarter: "Q1" },

  // ── 5 new adhoc requests (approved — each spawned an adhoc project) ─────────
  { id: "r4", title: "Emergency Content Takedown Tool", description: "Legal flagged content requiring immediate takedown capability. Needed a dedicated tool to remove content in under 1 hour across all platforms without engineering intervention.",
    requestedBy: "Priya Iyer", successMetric: "Remove flagged content in <1 hr", urgency: "high", category: "Miscellaneous",
    resources: { E: 1, T: 1, D: 0 }, targetDate: d(44),
    impacts: [{ projectId: "p16", delayDays: 7, newDate: d(63) }],
    status: "approved", createdAt: d(28), decisionDeadline: d(30), decidedAt: d(29), decidedBy: "Neha Verma",
    decisionComment: "Legal obligation — approved immediately. CTV Remote Navigation pushed 7 days.", quarter: "Q1" },
  { id: "r5", title: "Awards Season Homepage Takeover", description: "High-profile awards night requires a custom homepage experience with live countdown, nominee showcases, and surge traffic preparation to avoid degradation.",
    requestedBy: "Sanjay Bhatt", successMetric: "+30% concurrent users handled on awards night", urgency: "high", category: "Engagement",
    resources: { E: 2, T: 1, D: 1 }, targetDate: d(63),
    impacts: [{ projectId: "p7", delayDays: 7, newDate: d(91) }],
    status: "approved", createdAt: d(45), decisionDeadline: d(47), decidedAt: d(46), decidedBy: "Neha Verma",
    decisionComment: "Brand visibility play — proceed. Watch Party Beta shifted by 7 days.", quarter: "Q1" },
  { id: "r6", title: "Regional Language Quick Add", description: "Three regional language packs (Bhojpuri, Odia, Punjabi) to be added ahead of regional election news cycle to capture audience growth in Tier 2/3 cities.",
    requestedBy: "Neha Verma", successMetric: "Ship 3 new regional language packs in 2 weeks", urgency: "medium", category: "Discovery",
    resources: { E: 1, T: 1, D: 0 }, targetDate: d(49),
    impacts: [{ projectId: "p13", delayDays: 5, newDate: d(75) }],
    status: "approved", createdAt: d(32), decisionDeadline: d(35), decidedAt: d(34), decidedBy: "Sanjay Bhatt",
    decisionComment: "Time-sensitive growth play — approved. Smart Content Tagging nudged by 5 days.", quarter: "Q1" },
  { id: "r7", title: "OTT Partner API Integration", description: "Jio and Vi want a bundled subscription deal. Custom API integration required for seamless onboarding, entitlement sync, and co-branding across both partners.",
    requestedBy: "Karan Joshi", successMetric: "Go-live with 2 new telco partner bundles", urgency: "high", category: "Subscription",
    resources: { E: 2, T: 1, D: 0 }, targetDate: d(63),
    impacts: [{ projectId: "p15", delayDays: 7, newDate: d(84) }],
    status: "approved", createdAt: d(38), decisionDeadline: d(40), decidedAt: d(39), decidedBy: "Neha Verma",
    decisionComment: "Revenue-critical opportunity — approved. Subscriber Tier Upgrade Flow pushed by 7 days.", quarter: "Q1" },
  { id: "r8", title: "Live Event Score Overlay", description: "Sports product team needs a real-time score overlay widget for ongoing live cricket and kabaddi broadcasts to boost concurrent viewer engagement and watch time.",
    requestedBy: "Sanjay Bhatt", successMetric: "Real-time score overlay for 5 live events", urgency: "medium", category: "Linear",
    resources: { E: 1, T: 1, D: 0 }, targetDate: d(70),
    impacts: [{ projectId: "p10", delayDays: 5, newDate: d(89) }],
    status: "approved", createdAt: d(50), decisionDeadline: d(53), decidedAt: d(52), decidedBy: "Neha Verma",
    decisionComment: "High engagement potential — approved. Offline Downloads HDR shifted by 5 days.", quarter: "Q1" },
];

export const seedAudit: AuditEntry[] = [
  { id: "a1", timestamp: d(20), actor: "Sanjay Bhatt", type: "request_created", summary: "Raised ad-hoc request: Cricket Live Stream Promo", requestId: "r1" },
  { id: "a2", timestamp: d(21), actor: "Neha Verma", type: "approved", summary: "Approved Cricket Live Stream Promo — delays Continue Watching v2 by 14 days", requestId: "r1" },
  { id: "a3", timestamp: d(21), actor: "system", type: "timeline_shift", summary: "Continue Watching v2 shifted by +14 days", requestId: "r1", projectId: "p1" },
  { id: "a4", timestamp: d(40), actor: "Priya Iyer", type: "request_created", summary: "Raised ad-hoc request: EU Ads Disclosure", requestId: "r2" },
  { id: "a5", timestamp: d(42), actor: "Karan Joshi", type: "request_created", summary: "Raised ad-hoc request: Reliance Bundle", requestId: "r3" },
  { id: "a6", timestamp: d(28), actor: "Priya Iyer", type: "request_created", summary: "Raised ad-hoc request: Emergency Content Takedown Tool", requestId: "r4" },
  { id: "a7", timestamp: d(29), actor: "Neha Verma", type: "approved", summary: "Approved Emergency Content Takedown Tool — CTV Remote Navigation pushed 7 days", requestId: "r4" },
  { id: "a8", timestamp: d(29), actor: "system", type: "timeline_shift", summary: "CTV Remote Navigation shifted by +7 days", requestId: "r4", projectId: "p16" },
  { id: "a9", timestamp: d(45), actor: "Sanjay Bhatt", type: "request_created", summary: "Raised ad-hoc request: Awards Season Homepage Takeover", requestId: "r5" },
  { id: "a10", timestamp: d(46), actor: "Neha Verma", type: "approved", summary: "Approved Awards Season Homepage Takeover — Watch Party Beta pushed 7 days", requestId: "r5" },
  { id: "a11", timestamp: d(46), actor: "system", type: "timeline_shift", summary: "Watch Party Beta shifted by +7 days", requestId: "r5", projectId: "p7" },
  { id: "a12", timestamp: d(32), actor: "Neha Verma", type: "request_created", summary: "Raised ad-hoc request: Regional Language Quick Add", requestId: "r6" },
  { id: "a13", timestamp: d(34), actor: "Sanjay Bhatt", type: "approved", summary: "Approved Regional Language Quick Add — Smart Content Tagging nudged 5 days", requestId: "r6" },
  { id: "a14", timestamp: d(34), actor: "system", type: "timeline_shift", summary: "Smart Content Tagging shifted by +5 days", requestId: "r6", projectId: "p13" },
  { id: "a15", timestamp: d(38), actor: "Karan Joshi", type: "request_created", summary: "Raised ad-hoc request: OTT Partner API Integration", requestId: "r7" },
  { id: "a16", timestamp: d(39), actor: "Neha Verma", type: "approved", summary: "Approved OTT Partner API Integration — Subscriber Tier Upgrade Flow pushed 7 days", requestId: "r7" },
  { id: "a17", timestamp: d(39), actor: "system", type: "timeline_shift", summary: "Subscriber Tier Upgrade Flow shifted by +7 days", requestId: "r7", projectId: "p15" },
  { id: "a18", timestamp: d(50), actor: "Sanjay Bhatt", type: "request_created", summary: "Raised ad-hoc request: Live Event Score Overlay", requestId: "r8" },
  { id: "a19", timestamp: d(52), actor: "Neha Verma", type: "approved", summary: "Approved Live Event Score Overlay — Offline Downloads HDR shifted 5 days", requestId: "r8" },
  { id: "a20", timestamp: d(52), actor: "system", type: "timeline_shift", summary: "Offline Downloads HDR shifted by +5 days", requestId: "r8", projectId: "p10" },
];
